In [22]:
# pip install pip==20.1.1

# !python -m pip uninstall tensorflow --yes

# %pip install --ignore-installed --user pandas==1.0.5
# --no-deps 

# %pip install --no-deps --ignore-installed --user numpy==1.24.3

%pip install --no-deps --ignore-installed --user --force numpy==1.13.3

# %pip install --ignore-installed --user tensorflow==1.12.0

Collecting numpy==1.13.3
  Using cached numpy-1.13.3.zip (5.0 MB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Building wheels for collected packages: numpy
  Building wheel for numpy (setup.py): started
Note: you may need to restart the kernel to use updated packages.

  error: subprocess-exited-with-error

  python setup.py bdist_wheel did not run successfully.
  exit code: 1

  [157 lines of output]
  Running from numpy source directory.
  C:\Users\rtaylor\AppData\Local\Temp\pip-install-_s3a3ga_\numpy_16f407c330c14b81b3539ba6b986a284\numpy\distutils\misc_util.py:469: SyntaxWarning: "is" with a literal. Did you mean "=="?
    return is_string(s) and ('*' in s or '?' is s)
  blas_opt_info:
  blas_mkl_info:
    libraries mkl_rt not found in ['C:\\Users\\rtaylor\\Anaconda3\\lib', 'C:\\', 'C:\\Users\\rtaylor\\Anaconda3\\libs']
    NOT AVAILABLE

  blis_info:
    libraries blis not found in ['C:\\Users\\rtaylor\\Anaconda3\\lib', 'C:\\', 'C:\\Users\\rtaylor\\Anaconda3\\libs']
    NOT AVAILABLE

  Building wheel for numpy (setup.py): finished with status 'error'
  Running setup.py clean for numpy
Failed to build numpy

  openblas_info:
    libraries openblas not found in ['C:\\Users\\rtaylor\\Anaconda3\\lib', 'C:\\', 'C:\\Users\\rtaylor\\Anaconda3\\libs']
    NOT AVAILABLE

  atlas_3_10_blas_threads_info:
  Setting PTATLAS=ATLAS
    libraries tatlas not found in ['C:\\Users\\rtaylor\\Anaconda3\\lib', 'C:\\', 'C:\\Users\\rtaylor\\Anaconda3\\libs']
    NOT AVAILABLE

  atlas_3_10_blas_info:
    libraries satlas not found in ['C:\\Users\\rtaylor\\Anaconda3\\lib', 'C:\\', 'C:\\Users\\rtaylor\\Anaconda3\\libs']
    NOT AVAILABLE

  atlas_blas_threads_info:
  Setting PTATLAS=ATLAS
    libraries ptf77blas,ptcblas,atlas not found in ['C:\\Users\\rtaylor\\Anaconda3\\lib', 'C:\\', 'C:\\Users\\rtaylor\\Anaconda3\\libs']
    NOT AVAILABLE

  atlas_blas_info:
    libraries f77blas,cblas,atlas not found in ['C:\\Users\\rtaylor\\Anaconda3\\lib', 'C:\\', 'C:\\Users\\rtaylor\\Anaconda3\\libs']
    NOT AVAILABLE

  C:\Users\rtaylor\AppData\Local\Temp\pip-install-_s3a3ga_\numpy_16f407c330c14b81b3539ba6b986a284\numpy\distutils\system_info.py:572: UserWarning:
      Atlas (http://math-atlas.sourceforge.net/) libraries not found.
      Directories to search for the libraries can be specified in the
      numpy/distutils/site.cfg file (section [atlas]) or by setting
      the ATLAS environment variable.
    self.calc_info()
  blas_info:
    libraries blas not found in ['C:\\Users\\rtaylor\\Anaconda3\\lib', 'C:\\', 'C:\\Users\\rtaylor\\Anaconda3\\libs']
    NOT AVAILABLE

  C:\Users\rtaylor\AppData\Local\Temp\pip-install-_s3a3ga_\numpy_16f407c330c14b81b3539ba6b986a284\numpy\distutils\system_info.py:572: UserWarning:
      Blas (http://www.netlib.org/blas/) libraries not found.
      Directories to search for the libraries can be specified in the
      numpy/distutils/site.cfg file (section [blas]) or by setting
      the BLAS environment variable.
    self.calc_info()
  blas_src_info:
    NOT AVAILABLE

  C:\Users\rtaylor\AppData\Local\Temp\pip-install-_s3a3ga_\numpy_16f407c330c14b81b3539ba6b986a284\numpy\distutils\system_info.py:572: UserWarning:
      Blas (http://www.netlib.org/blas/) sources not found.
      Directories to search for the sources can be specified in the
      numpy/distutils/site.cfg file (section [blas_src]) or by setting
      the BLAS_SRC environment variable.
    self.calc_info()
    NOT AVAILABLE

  'svnversion' is not recognized as an internal or external command,
  operable program or batch file.
  'svnversion' is not recognized as an internal or external command,
  operable program or batch file.
  non-existing path in 'numpy\\distutils': 'site.cfg'
  F2PY Version 2
  lapack_opt_info:
  lapack_mkl_info:
    libraries mkl_rt not found in ['C:\\Users\\rtaylor\\Anaconda3\\lib', 'C:\\', 'C:\\Users\\rtaylor\\Anaconda3\\libs']
    NOT AVAILABLE

  openblas_lapack_info:
    libraries openblas not found in ['C:\\Users\\rtaylor\\Anaconda3\\lib', 'C:\\', 'C:\\Users\\rtaylor\\Anaconda3\\libs']
    NOT AVAILABLE

  atlas_3_10_threads_info:
  Setting PTATLAS=ATLAS
    libraries tatlas,tatlas not found in C:\Users\rtaylor\Anaconda3\lib
    libraries lapack_atlas not found in C:\Users\rtaylor\Anaconda3\lib
    libraries tatlas,tatlas not found in C:\
    libraries lapack_atlas not found in C:\
    libraries tatlas,tatlas not found in C:\Users\rtaylor\Anaconda3\libs
    libraries lapack_atlas not found in C:\Users\rtaylor\Anaconda3\libs
  <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
    NOT AVAILABLE

  atlas_3_10_info:
    libraries satlas,satlas not found in C:\Users\rtaylor\Anaconda3\lib
    libraries lapack_atlas not found in C:\Users\rtaylor\Anaconda3\lib
    libraries satlas,satlas not found in C:\
    libraries lapack_atlas not found in C:\
    libraries satlas,satlas not found in C:\Users\rtaylor\Anaconda3\libs
    libraries lapack_atlas not found in C:\Users\rtaylor\Anaconda3\libs
  <class 'numpy.distutils.system_info.atlas_3_10_info'>
    NOT AVAILABLE

  atlas_threads_info:
  Setting PTATLAS=ATLAS
    libraries ptf77blas,ptcblas,atlas not found in C:\Users\rtaylor\Anaconda3\lib
    libraries lapack_atlas not found in C:\Users\rtaylor\Anaconda3\lib
    libraries ptf77blas,ptcblas,atlas not found in C:\
    libraries lapack_atlas not found in C:\
    libraries ptf77blas,ptcblas,atlas not found in C:\Users\rtaylor\Anaconda3\libs
    libraries lapack_atlas not found in C:\Users\rtaylor\Anaconda3\libs
  <class 'numpy.distutils.system_info.atlas_threads_info'>
    NOT AVAILABLE

  atlas_info:
    libraries f77blas,cblas,atlas not found in C:\Users\rtaylor\Anaconda3\lib
    libraries lapack_atlas not found in C:\Users\rtaylor\Anaconda3\lib
    libraries f77blas,cblas,atlas not found in C:\
    libraries lapack_atlas not found in C:\
    libraries f77blas,cblas,atlas not found in C:\Users\rtaylor\Anaconda3\libs
    libraries lapack_atlas not found in C:\Users\rtaylor\Anaconda3\libs
  <class 'numpy.distutils.system_info.atlas_info'>
    NOT AVAILABLE

  lapack_info:
    libraries lapack not found in ['C:\\Users\\rtaylor\\Anaconda3\\lib', 'C:\\', 'C:\\Users\\rtaylor\\Anaconda3\\libs']
    NOT AVAILABLE

  C:\Users\rtaylor\AppData\Local\Temp\pip-install-_s3a3ga_\numpy_16f407c330c14b81b3539ba6b986a284\numpy\distutils\system_info.py:572: UserWarning:
      Lapack (http://www.netlib.org/lapack/) libraries not found.
      Directories to search for the libraries can be specified in the
      numpy/distutils/site.cfg file (section [lapack]) or by setting
      the LAPACK environment variable.
    self.calc_info()
  lapack_src_info:
    NOT AVAILABLE

  C:\Users\rtaylor\AppData\Local\Temp\pip-install-_s3a3ga_\numpy_16f407c330c14b81b3539ba6b986a284\numpy\distutils\system_info.py:572: UserWarning:
      Lapack (http://www.netlib.org/lapack/) sources not found.
      Directories to search for the sources can be specified in the
      numpy/distutils/site.cfg file (section [lapack_src]) or by setting
      the LAPACK_SRC environment variable.
    self.calc_info()
    NOT AVAILABLE

  C:\Users\rtaylor\Anaconda3\lib\distutils\dist.py:274: UserWarning: Unknown distribution option: 'define_macros'
    warnings.warn(msg)
  running bdist_wheel
  running build
  running config_cc
  unifing config_cc, config, build_clib, build_ext, build commands --compiler options
  running config_fc
  unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
  running build_src
  build_src
  building py_modules sources
  creating build
  creating build\src.win-amd64-3.8
  creating build\src.win-amd64-3.8\numpy
  creating build\src.win-amd64-3.8\numpy\distutils
  building library "npymath" sources
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
  [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for numpy
  error: subprocess-exited-with-error

  python setup.py clean did not run successfully.
  exit code: 1

  [10 lines of output]
  Running from numpy source directory.

  `setup.py clean` is not supported, use one of the following instead:

    - `git clean -xdf` (cleans all files)
    - `git clean -Xdf` (cleans all versioned files, doesn't touch
                        files that aren't checked into the git repo)

  Add `--force` to your command to use it anyway if you must (unsupported).

  [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed cleaning build dir for numpy
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (numpy)

In [28]:
# upgrade pip
# %pip install --upgrade pip

# %pip install tensorflow

import tensorflow as tf

AttributeError: module 'numpy' has no attribute 'typeDict'

In [23]:
pip install pandas==1.5.3

Collecting pandas==1.5.3
  Downloading pandas-1.5.3-cp38-cp38-win_amd64.whl.metadata (12 kB)Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\rtaylor\appdata\roaming\python\python38\site-packages (from pandas==1.5.3) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\rtaylor\appdata\roaming\python\python38\site-packages (from pandas==1.5.3) (2024.2)
Requirement already satisfied: numpy>=1.20.3 in c:\users\rtaylor\appdata\roaming\python\python38\site-packages (from pandas==1.5.3) (1.24.3)
Requirement already satisfied: six>=1.5 in c:\users\rtaylor\appdata\roaming\python\python38\site-packages (from python-dateutil>=2.8.1->pandas==1.5.3) (1.16.0)
Downloading pandas-1.5.3-cp38-cp38-win_amd64.whl (11.0 MB)
   ---------------------------------------- 11.0/11.0 MB 7.8 MB/s eta 0:00:00

WARNING: Error parsing dependencies of pyodbc: Invalid version: '4.0.0-unsupported'
  WARNING: Failed to remove contents in a temporary directory 'C:\Users\rtaylor\Anaconda3\Lib\site-packages\~andas'.
  You can safely remove it manually.
ERROR: Exception:
Traceback (most recent call last):
  File "C:\Users\rtaylor\Anaconda3\lib\site-packages\pip\_internal\cli\base_command.py", line 105, in _run_wrapper
    status = _inner_run()
  File "C:\Users\rtaylor\Anaconda3\lib\site-packages\pip\_internal\cli\base_command.py", line 96, in _inner_run
    return self.run(options, args)
  File "C:\Users\rtaylor\Anaconda3\lib\site-packages\pip\_internal\cli\req_command.py", line 67, in wrapper
    return func(self, options, args)
  File "C:\Users\rtaylor\Anaconda3\lib\site-packages\pip\_internal\commands\install.py", line 483, in run
    installed_versions[distribution.canonical_name] = distribution.version
  File "C:\Users\rtaylor\Anaconda3\lib\site-packages\pip\_internal\metadata\pkg_resources.py", line 192, in version
    return parse_version(self._dist.version)
  File "C:\Users\rtaylor\Anaconda3\lib\site-packages\pip\_vendor\packaging\version.py", line 56, in parse
    return Version(version)
  File "C:\Users\rtaylor\Anaconda3\lib\site-packages\pip\_vendor\packaging\version.py", line 202, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
pip._vendor.packaging.version.InvalidVersion: Invalid version: '4.0.0-unsupported'

Installing collected packages: pandas
  Attempting uninstall: pandas
    Found existing installation: pandas 1.0.5
    Uninstalling pandas-1.0.5:
      Successfully uninstalled pandas-1.0.5

In [23]:
!python --version

Python 3.8.3

In [24]:
pip show tensorflow

Name: tensorflow
Version: 2.13.0
Summary: TensorFlow is an open source machine learning framework for everyone.
Home-page: https://www.tensorflow.org/
Author: Google Inc.
Author-email: packages@tensorflow.org
License: Apache 2.0
Location: c:\users\rtaylor\anaconda3\lib\site-packages
Requires: tensorflow-intel
Note: you may need to restart the kernel to use updated packages.Required-by:

In [25]:
pip show pandas

Name: pandas
Version: 1.0.5
Summary: Powerful data structures for data analysis, time series, and statistics
Home-page: https://pandas.pydata.org
Author:
Author-email:
License: BSD
Location: c:\users\rtaylor\appdata\roaming\python\python38\site-packages
Requires: numpy, python-dateutil, pytz
Required-by: seaborn, statsmodels
Note: you may need to restart the kernel to use updated packages.

In [26]:
pip show numpy

Name: numpy
Version: 1.24.3
Summary: Fundamental package for array computing in Python
Home-page: https://www.numpy.org
Author: Travis E. Oliphant et al.
Author-email:
License: BSD-3-Clause
Location: c:\users\rtaylor\appdata\roaming\python\python38\site-packages
Requires:
Required-by: astropy, bkcharts, bokeh, Bottleneck, h5py, imageio, matplotlib, mkl-fft, mkl-random, numba, numexpr, pandas, patsy, PyWavelets, scikit-learn, scipy, seaborn, statsmodels, tables, tensorboard, tensorflow-intel
Note: you may need to restart the kernel to use updated packages.

In [27]:
# Setup

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

np.random.seed(42)

C:\Users\rtaylor\AppData\Roaming\Python\Python38\site-packages\pandas\_testing.py:24: FutureWarning: In the future `np.bool` will be defined as the corresponding NumPy scalar.
  import pandas._libs.testing as _testing

AttributeError: module 'numpy' has no attribute 'bool'.
`np.bool` was a deprecated alias for the builtin `bool`. To avoid this error in existing code, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

In [4]:
# Import data

from pathlib import Path
cwd = Path.cwd()
datapath = (cwd.parent / 'data/').resolve()

df = pd.read_csv(datapath / 'RecessionTimingRawData2024.csv')

NameError: name 'pd' is not defined

In [15]:
# Set up columns

for i in (0,1,3,6,12):
    for var in ("ur",):
        if (i>0): df["s"+str(i)+"_"+var] = df[var].diff(i)
        df["l"+str(i)+"_"+var] = df[var].shift(i)
    for var in ('emp','sp500','ip'):
        if (i==0):
            df["ln"+var] = np.log(df[var])
        else:
            df["s"+str(i)+"_ln"+var] = np.log(df[var]).diff(i)
            df["l"+str(i)+"_ln"+var] = np.log(df[var]).shift(i)

for i in (1,2,3,4,5,6):
    for var in ('r10yr','rff','rbaa','r3mo','r1yr','r3yr','r5yr'):
        df["l"+str(i)+"_"+var] = df[var].shift(i)

df["rbaar10yr"] = df.rbaa - df.r10yr
df["r10yrr3yr"] = df.r10yr - df.r3yr
df["s3_r10yrr3yr"] = df.r10yrr3yr.diff(3)
# df["s12_rff"] = df.rff.diff(i) # not enough history...
        
df.head(24)

,period,r10yr,rff,rbaa,r3mo,r1yr,r3yr,r5yr,rec,rec12mo,...,l5_r1yr,l5_r3yr,l5_r5yr,l6_r10yr,l6_rff,l6_rbaa,l6_r3mo,l6_r1yr,l6_r3yr,l6_r5yr
0,4/1/1953,2.83,NaN,3.65,2.19,2.36,2.51,2.62,0.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,5/1/1953,3.05,NaN,3.78,2.16,2.48,2.72,2.87,0.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,6/1/1953,3.11,NaN,3.86,2.11,2.45,2.74,2.94,0.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,7/1/1953,2.93,NaN,3.86,2.04,2.38,2.62,2.75,0.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,8/1/1953,2.95,NaN,3.85,2.04,2.28,2.58,2.80,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,9/1/1953,2.87,NaN,3.88,1.79,2.20,2.56,2.71,1.0,1.0,...,2.36,2.51,2.62,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,10/1/1953,2.66,NaN,3.82,1.38,1.79,2.23,2.43,1.0,1.0,...,2.48,2.72,2.87,2.83,NaN,3.65,2.19,2.36,2.51,2.62
7,11/1/1953,2.68,NaN,3.75,1.44,1.67,2.20,2.42,1.0,1.0,...,2.45,2.74,2.94,3.05,NaN,3.78,2.16,2.48,2.72,2.87
8,12/1/1953,2.59,NaN,3.74,1.60,1.66,2.07,2.32,1.0,1.0,...,2.38,2.62,2.75,3.11,NaN,3.86,2.11,2.45,2.74,2.94
9,1/1/1954,2.48,NaN,3.71,1.18,1.41,1.89,2.17,1.0,1.0,...,2.28,2.58,2.80,2.93,NaN,3.86,2.04,2.38,2.62,2.75
10,2/1/1954,2.47,NaN,3.61,0.97,1.14,1.63,2.04,1.0,1.0,...,2.20,2.56,2.71,2.95,NaN,3.85,2.04,2.28,2.58,2.80
11,3/1/1954,2.37,NaN,3.51,1.03,1.13,1.59,1.93,1.0,1.0,...,1.79,2.23,2.43,2.87,NaN,3.88,1.79,2.20,2.56,2.71
12,4/1/1954,2.29,NaN,3.47,0.97,0.96,1.54,1.87,1.0,1.0,...,1.67,2.20,2.42,2.66,NaN,3.82,1.38,1.79,2.23,2.43
13,5/1/1954,2.37,NaN,3.47,0.76,0.85,1.56,1.92,1.0,1.0,...,1.66,2.07,2.32,2.68,NaN,3.75,1.44,1.67,2.20,2.42
14,6/1/1954,2.38,NaN,3.49,0.64,0.82,1.53,1.92,0.0,0.0,...,1.41,1.89,2.17,2.59,NaN,3.74,1.60,1.66,2.07,2.32
15,7/1/1954,2.30,0.80,3.50,0.72,0.84,1.47,1.85,0.0,0.0,...,1.14,1.63,2.04,2.48,NaN,3.71,1.18,1.41,1.89,2.17
16,8/1/1954,2.36,1.22,3.49,0.92,0.88,1.49,1.90,0.0,0.0,...,1.13,1.59,1.93,2.47,NaN,3.61,0.97,1.14,1.63,2.04
17,9/1/1954,2.38,1.06,3.47,1.01,1.03,1.60,1.96,0.0,0.0,...,0.96,1.54,1.87,2.37,NaN,3.51,1.03,1.13,1.59,1.93
18,10/1/1954,2.43,0.85,3.46,0.98,1.17,1.72,2.02,0.0,0.0,...,0.85,1.56,1.92,2.29,NaN,3.47,0.97,0.96,1.54,1.87
19,11/1/1954,2.48,0.83,3.45,0.93,1.14,1.75,2.09,0.0,0.0,...,0.82,1.53,1.92,2.37,NaN,3.47,0.76,0.85,1.56,1.92
20,12/1/1954,2.51,1.28,3.45,1.15,1.21,1.81,2.16,0.0,0.0,...,0.84,1.47,1.85,2.38,NaN,3.49,0.64,0.82,1.53,1.92
21,1/1/1955,2.61,1.39,3.45,1.22,1.39,1.99,2.32,0.0,0.0,...,0.88,1.49,1.90,2.30,0.80,3.50,0.72,0.84,1.47,1.85
22,2/1/1955,2.65,1.29,3.47,1.17,1.57,2.12,2.38,0.0,0.0,...,1.03,1.60,1.96,2.36,1.22,3.49,0.92,0.88,1.49,1.90
23,3/1/1955,2.68,1.35,3.48,1.28,1.59,2.26,2.48,0.0,0.0,...,1.17,1.72,2.02,2.38,1.06,3.47,1.01,1.03,1.60,1.96

In [16]:
df.columns

Index(['period', 'r10yr', 'rff', 'rbaa', 'r3mo', 'r1yr', 'r3yr', 'r5yr', 'rec',
       'rec12mo', 'r10yrff', 'emp', 'ur', 'sp500', 'ip', 'cycle', 'r10yrffma',
       's6_lnsp500', 's6_lnemp', 's6_lnip', 'l0_ur', 'lnemp', 'lnsp500',
       'lnip', 's1_ur', 'l1_ur', 's1_lnemp', 'l1_lnemp', 's1_lnsp500',
       'l1_lnsp500', 's1_lnip', 'l1_lnip', 's3_ur', 'l3_ur', 's3_lnemp',
       'l3_lnemp', 's3_lnsp500', 'l3_lnsp500', 's3_lnip', 'l3_lnip', 's6_ur',
       'l6_ur', 'l6_lnemp', 'l6_lnsp500', 'l6_lnip', 's12_ur', 'l12_ur',
       's12_lnemp', 'l12_lnemp', 's12_lnsp500', 'l12_lnsp500', 's12_lnip',
       'l12_lnip', 'rbaar10yr', 'r10yrr3yr', 's3_r10yrr3yr', 'l1_r10yr',
       'l1_rff', 'l1_rbaa', 'l1_r3mo', 'l1_r1yr', 'l1_r3yr', 'l1_r5yr',
       'l2_r10yr', 'l2_rff', 'l2_rbaa', 'l2_r3mo', 'l2_r1yr', 'l2_r3yr',
       'l2_r5yr', 'l3_r10yr', 'l3_rff', 'l3_rbaa', 'l3_r3mo', 'l3_r1yr',
       'l3_r3yr', 'l3_r5yr', 'l4_r10yr', 'l4_rff', 'l4_rbaa', 'l4_r3mo',
       'l4_r1yr', 'l4_r3yr', 'l4_r5yr', 'l5_r10yr', 'l5_rff', 'l5_rbaa',
       'l5_r3mo', 'l5_r1yr', 'l5_r3yr', 'l5_r5yr', 'l6_r10yr', 'l6_rff',
       'l6_rbaa', 'l6_r3mo', 'l6_r1yr', 'l6_r3yr', 'l6_r5yr'],
      dtype='object')

In [21]:
# Select subset of data

# xlist = ['r10yrffma','r10yr','rff','rbaa','r3mo','r1yr','r3yr','r5yr','ur','s6_lnsp500','s6_lnemp','s6_lnip','s6_ur','s12_ur','s12_lnemp','s12_lnsp500','s12_lnip']
# xlist = ['r10yrffma','rbaar10yr','r10yrr3yr','r10yr','rff','rbaa','r3mo','r1yr','r3yr','r5yr','ur','s3_ur','s3_lnemp','s3_lnsp500','s6_lnsp500','s6_lnemp','s6_lnip','s6_ur','s12_ur','s12_lnemp','s12_lnsp500','s12_lnip']
# xlist = ['r10yrffma','s6_lnsp500','s6_lnemp']
# xlist = ['r10yrffma','s6_lnsp500','s6_lnemp','s3_ur','s6_lnip','rbaar10yr','r10yrr3yr']
xlist = ['lnemp','l1_lnemp','l3_lnemp','l6_lnemp','l12_lnemp',
         'ur','l1_ur','l3_ur','l6_ur','l12_ur',
         'lnsp500','l1_lnsp500','l3_lnsp500','l6_lnsp500','l12_lnsp500',
         'lnip','l1_lnip','l3_lnip','l6_lnip','l12_lnip',
         'r10yr','l1_r10yr','l2_r10yr','l3_r10yr','l4_r10yr','l5_r10yr','l6_r10yr',
         'rff','l1_rff','l2_rff','l3_rff','l4_rff','l5_rff',
         'rbaa','l1_rbaa','l2_rbaa','l3_rbaa','l4_rbaa','l5_rbaa','l6_rbaa',
         'r3yr','l1_r3yr','l2_r3yr','l3_r3yr','l4_r3yr','l5_r3yr','l6_r3yr'] # 'l6_rff',

# df2_oos = df[["period","rec12mo"]+xlist][~np.isnan(df.r10yrffma) & np.isnan(df.rec)]
df2_oos = df[["period","rec12mo"]+xlist][df.index>=779] # 791

df2_valid = df2_oos[df2_oos.index<=804]

# df2 = df[["period","rec12mo"]+xlist][~np.isnan(df.r10yrffma) & ~np.isnan(df.rec)]
df2 = df[["period","rec12mo"]+xlist][~np.isnan(df.r10yrffma) & ~np.isnan(df.rec)]
df2 = df2[df2.index<779]
df2

,period,rec12mo,lnemp,l1_lnemp,l3_lnemp,l6_lnemp,l12_lnemp,ur,l1_ur,l3_ur,...,l4_rbaa,l5_rbaa,l6_rbaa,r3yr,l1_r3yr,l2_r3yr,l3_r3yr,l4_r3yr,l5_r3yr,l6_r3yr
20,12/1/1954,0.0,10.806308,10.803242,10.797246,10.797430,10.813821,5.0,5.3,6.1,...,3.49,3.50,3.49,1.81,1.75,1.72,1.60,1.49,1.47,1.53
21,1/1/1955,0.0,10.809647,10.806308,10.798391,10.796203,10.809101,4.9,5.0,5.7,...,3.47,3.49,3.50,1.99,1.81,1.75,1.72,1.60,1.49,1.47
22,2/1/1955,0.0,10.812633,10.809647,10.803242,10.796018,10.807341,4.7,4.9,5.3,...,3.46,3.47,3.49,2.12,1.99,1.81,1.75,1.72,1.60,1.49
23,3/1/1955,0.0,10.819018,10.812633,10.806308,10.797246,10.802775,4.6,4.7,5.0,...,3.45,3.46,3.47,2.26,2.12,1.99,1.81,1.75,1.72,1.60
24,4/1/1955,0.0,10.824726,10.819018,10.809647,10.798391,10.803222,4.7,4.6,4.9,...,3.45,3.45,3.46,2.37,2.26,2.12,1.99,1.81,1.75,1.72
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
774,10/1/2017,0.0,11.899181,11.898181,11.896636,11.892546,11.884965,4.2,4.3,4.3,...,4.37,4.55,4.57,1.68,1.51,1.48,1.54,1.49,1.48,1.44
775,11/1/2017,0.0,11.900736,11.899181,11.897555,11.894023,11.885785,4.2,4.2,4.4,...,4.39,4.37,4.55,1.81,1.68,1.51,1.48,1.54,1.49,1.48
776,12/1/2017,0.0,11.901726,11.900736,11.898181,11.895381,11.887313,4.1,4.2,4.3,...,4.31,4.39,4.37,1.96,1.81,1.68,1.51,1.48,1.54,1.49
777,1/1/2018,0.0,11.902715,11.901726,11.899181,11.896636,11.888866,4.0,4.1,4.2,...,4.30,4.31,4.39,2.15,1.96,1.81,1.68,1.51,1.48,1.54
778,2/1/2018,0.0,11.905332,11.902715,11.900736,11.897555,11.890320,4.1,4.0,4.2,...,4.32,4.30,4.31,2.36,2.15,1.96,1.81,1.68,1.51,1.48

In [138]:
df2.columns

Index(['period', 'rec12mo', 'lnemp', 'l1_lnemp', 'l3_lnemp', 'l6_lnemp',
       'l12_lnemp', 'ur', 'l1_ur', 'l3_ur', 'l6_ur', 'l12_ur', 'lnsp500',
       'l1_lnsp500', 'l3_lnsp500', 'l6_lnsp500', 'l12_lnsp500', 'lnip',
       'l1_lnip', 'l3_lnip', 'l6_lnip', 'l12_lnip', 'r10yr', 'l1_r10yr',
       'l2_r10yr', 'l3_r10yr', 'l4_r10yr', 'l5_r10yr', 'l6_r10yr', 'rff',
       'l1_rff', 'l2_rff', 'l3_rff', 'l4_rff', 'l5_rff', 'rbaa', 'l1_rbaa',
       'l2_rbaa', 'l3_rbaa', 'l4_rbaa', 'l5_rbaa', 'l6_rbaa', 'r3yr',
       'l1_r3yr', 'l2_r3yr', 'l3_r3yr', 'l4_r3yr', 'l5_r3yr', 'l6_r3yr'],
      dtype='object')

In [ ]:
# Scatter plot of SP500 vs Emp (during recessions and expansions)

fig, ax = plt.subplots()
sc = df2.plot.scatter(x='s6_lnsp500', y='r10yrffma', c='rec12mo', colormap='winter', ax=ax) # rainbow

In [ ]:
# axes = pd.plotting.scatter_matrix(df2, alpha = 0.2, figsize = (9, 9), range_padding = 0.15)

In [267]:
from sklearn.model_selection import train_test_split

y = df2["rec12mo"]
X = df2[xlist]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42) # 0.33

y_valid = df2_valid["rec12mo"]
X_valid = df2_valid[xlist]

y_oos = df2_oos["rec12mo"]
X_oos = df2_oos[xlist]

In [268]:
# Scale

from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
ss.fit(X_train)
X_train = pd.DataFrame(ss.transform(X_train), columns=X_train.columns, index=X_train.index)
X_test = pd.DataFrame(ss.transform(X_test), columns=X_test.columns, index=X_test.index)
X_valid = pd.DataFrame(ss.transform(X_valid), columns=X_valid.columns, index=X_valid.index)
X_oos = pd.DataFrame(ss.transform(X_oos), columns=X_oos.columns, index=X_oos.index)

print(ss.scale_)

[0.3361544  0.33657984 0.33739686 0.33855491 0.34081369 1.53128309
 1.53250761 1.54078805 1.55516289 1.59296429 1.28260219 1.28274542
 1.28130758 1.27920557 1.27957573 0.49844093 0.49937029 0.5013119
 0.50424319 0.51027171 2.82774033 2.82177552 2.80879993 2.80096874
 2.79220041 2.78444926 2.77177976 3.65506856 3.6571577  3.63253738
 3.6333993  3.64233478 3.61989316 2.90454886 2.89688208 2.88527778
 2.87835553 2.87265362 2.86685834 2.8548704  3.15976171 3.15416314
 3.14063869 3.12861439 3.12466697 3.11345437 3.10016277]

In [263]:
# Models: Logistic, Random Forest, SVC, Voting Classifier

from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import VotingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
from sklearn.neural_network import MLPClassifier

log_clf = LogisticRegression(random_state=42,max_iter=1000)
rnd_clf = RandomForestClassifier(random_state=42)
svm_clf = SVC(random_state=42, probability=True)
voting_clf = VotingClassifier(estimators=[('lr', log_clf), ('rf', rnd_clf), ('svc', svm_clf)], voting='soft') # hard
mlp_clf = MLPClassifier(hidden_layer_sizes=[50,3,2],random_state=42,max_iter=2000,activation='logistic',alpha=0.001)

voting_clf.fit(X_train, y_train)

for clf in (log_clf, rnd_clf, svm_clf, voting_clf, mlp_clf):
    clf.fit(X_train, y_train)
    y_pred = clf.predict(X_test)
    print(clf.__class__.__name__, accuracy_score(y_test, y_pred))

LogisticRegression 0.8881578947368421
RandomForestClassifier 0.9868421052631579
SVC 0.9144736842105263
VotingClassifier 0.9736842105263158
MLPClassifier 0.8881578947368421

In [420]:
# nn diff parameters?

# without standardscalerscaler
# mlp_clf2 = MLPClassifier(hidden_layer_sizes=[10],random_state=42,max_iter=2000,activation='relu',solver='sgd',alpha=0.1) # 0.8846
# mlp_clf2 = MLPClassifier(hidden_layer_sizes=[22],random_state=42,max_iter=2000,activation='relu',solver='sgd',alpha=0.1) # 0.9615
# mlp_clf2 = MLPClassifier(hidden_layer_sizes=[22,11,5],random_state=42,max_iter=2000,activation='relu',solver='sgd',alpha=0.01) # 1.0

# with standardscaler
mlp_clf2 = MLPClassifier(hidden_layer_sizes=[20,10],random_state=42,max_iter=2500,activation='logistic',solver='lbfgs',alpha=1) # 0.9615

mlp_clf2.fit(X_train, y_train)
y_pred = mlp_clf2.predict(X_test)
print(mlp_clf2.__class__.__name__, accuracy_score(y_test, y_pred))
y_pred_valid = mlp_clf2.predict(X_valid)
print(mlp_clf2.__class__.__name__, accuracy_score(y_valid, y_pred_valid))

MLPClassifier 0.9868421052631579
MLPClassifier 0.9615384615384616

In [421]:
print(mlp_clf2.coefs_)
print(mlp_clf2.intercepts_)

[array([[-3.05042069e-01, -1.75552546e-02, -1.82323765e-01,
        -4.83550871e-01,  7.50991181e-02,  1.10110817e-01,
         1.26722681e-01, -1.53922974e-01,  1.66612951e-02,
        -1.83723649e-01, -1.79718863e-01, -4.35028231e-02,
        -1.56294020e-01,  3.67769521e-01,  7.70270634e-02,
         5.37165640e-02,  2.63827977e-02, -4.43153618e-02,
        -6.63156837e-03,  1.25747499e-01],
       [-2.66591795e-01, -3.03002481e-02, -2.03935718e-01,
        -4.46512605e-01,  6.91134031e-02,  1.33106599e-01,
         1.02818462e-01, -1.28463673e-01,  2.11788385e-02,
        -2.05302149e-01, -2.00956640e-01, -8.95326487e-03,
        -1.75893324e-01,  3.63183732e-01,  7.08984554e-02,
         3.82903725e-02,  2.22294048e-02, -2.42330648e-02,
        -1.09349173e-02,  1.10965449e-01],
       [-2.49074502e-01, -4.21610593e-02, -2.25522609e-01,
        -4.19050221e-01,  6.52262518e-02,  1.56367768e-01,
         8.53136930e-02, -1.15037606e-01,  2.51499860e-02,
        -2.27003971e-01, -2.22117728e-01,  1.60049499e-02,
        -1.95875101e-01,  3.43286251e-01,  6.68785601e-02,
         2.76783460e-02,  1.89710447e-02, -1.03163733e-02,
        -1.44626332e-02,  1.11110914e-01],
       [-1.86359083e-01, -6.32820610e-02, -2.63380232e-01,
        -3.70294862e-01,  6.42474153e-02,  1.91149704e-01,
         7.08552539e-02, -8.57919157e-02,  2.28149960e-02,
        -2.65102401e-01, -2.58725024e-01,  6.44612637e-02,
        -2.28219513e-01,  3.12296824e-01,  6.58964568e-02,
         1.04918738e-02,  2.07863805e-02,  1.38340268e-02,
        -1.18461460e-02,  7.29476664e-02],
       [-1.64766792e-01, -7.80327936e-02, -3.00062277e-01,
        -3.45804958e-01,  6.88371002e-02,  2.30360339e-01,
         9.10741631e-02, -8.34369636e-02,  1.41288293e-02,
        -3.01811589e-01, -2.94313589e-01,  8.40228789e-02,
        -2.60218381e-01,  2.57792156e-01,  7.05669727e-02,
         9.36922638e-03,  2.69263878e-02,  1.82088945e-02,
        -2.67811328e-03,  2.24832365e-02],
       [-7.21976865e-02, -3.13317034e-01, -6.12960699e-01,
         4.14606743e-02,  1.48504043e-01,  5.70902486e-01,
         1.61628068e-01,  4.31975374e-01, -2.64577502e-01,
        -6.13702030e-01, -5.94959345e-01,  4.08290987e-01,
        -5.51667030e-01, -4.35153981e-01,  1.21421181e-01,
        -1.36186085e-01,  2.32605412e-01,  1.88423305e-01,
         2.67156591e-01, -5.78790328e-01],
       [-3.39541917e-01, -2.08731019e-01, -3.37944457e-01,
        -2.82834979e-01,  2.20214146e-01,  2.70828085e-01,
         4.15091632e-01,  2.41145069e-01, -3.37709682e-01,
        -3.40228520e-01, -3.27891460e-01,  1.16646601e-01,
        -2.97354454e-01, -3.68520525e-01,  1.93238538e-01,
         8.04385039e-03,  2.94508797e-01,  6.43705427e-03,
         3.38400068e-01, -5.06596079e-01],
       [-2.07345892e-01, -8.03462510e-02,  5.84107489e-02,
        -1.39893615e-01,  2.35516117e-01, -1.04332057e-01,
         5.51836115e-01,  2.48227663e-01, -3.10299908e-01,
         5.71818627e-02,  5.63013370e-02, -5.40715259e-02,
         7.06718578e-02, -2.33887293e-01,  2.27081312e-01,
         9.60276415e-02,  2.74881582e-01, -8.44185937e-02,
         3.06922700e-01, -6.57963065e-01],
       [-6.14009266e-01, -5.43301289e-02,  3.15429689e-01,
        -2.45081480e-01,  2.53365842e-01, -3.13325537e-01,
         5.96625479e-01,  1.41610937e-01, -3.26872213e-01,
         3.17656578e-01,  3.08908705e-01, -3.13170554e-01,
         2.89903108e-01,  1.17444843e-01,  2.35360041e-01,
         2.06252231e-01,  2.77482028e-01, -2.21266616e-01,
         3.21162303e-01, -4.60593495e-01],
       [-5.14164425e-01, -9.49821509e-02,  6.97834598e-01,
         3.86378139e-02,  1.85146562e-01, -7.15630005e-01,
         3.62839585e-01,  3.07699209e-01, -1.93111927e-01,
         7.00444921e-01,  6.82503080e-01, -3.27089753e-01,
         6.27987127e-01,  5.86177348e-01,  1.74665591e-01,
         1.58293723e-01,  1.72482882e-01, -1.72629284e-01,
         1.84936810e-01, -1.15197081e-01],
       [-2.68983603e-01, -2.99985956e-02,  1.01002806e-01,
        -4.73951213e-01,  1.21922137e-01, -2.64252490e-01,
         1.40915649e-01, -3.23265062e-01,  5.68500801e-02,
         9.74744965e-02,  9.83445114e-02, -2.58160785e-01,
         1.14358726e-01,  1.78999746e-01,  1.31193744e-01,
         1.60831987e-01,  1.47186571e-02, -1.70596114e-01,
        -4.05447024e-02,  4.38965020e-01],
       [-2.36759602e-01, -5.64502450e-02,  1.30463016e-02,
        -3.94784639e-01,  8.37098050e-02, -1.52589507e-01,
         1.05194667e-01, -2.70144661e-01,  8.53283063e-02,
         9.86033380e-03,  1.22053449e-02, -1.41393173e-01,
         3.29203046e-02,  2.14948691e-01,  9.36785829e-02,
         1.04330255e-01, -1.28277796e-02, -1.01971079e-01,
        -6.90001024e-02,  3.25734836e-01],
       [-2.35503336e-01, -1.16827736e-01, -1.19715093e-01,
        -3.53101743e-01,  4.50791840e-02, -3.10592486e-04,
         5.22442814e-02, -2.29246232e-01,  1.00095563e-01,
        -1.22251636e-01, -1.17204959e-01, -1.34166785e-02,
        -8.92135470e-02,  2.36461895e-01,  5.26877639e-02,
         4.15468122e-02, -2.87041935e-02, -2.70179488e-02,
        -8.61856890e-02,  1.96851679e-01],
       [-7.69223385e-02, -5.86282010e-02, -1.35604772e-01,
        -2.07908579e-01,  1.15036737e-02,  3.76460687e-02,
         7.53687378e-03, -1.72092105e-01,  1.64700059e-01,
        -1.37307690e-01, -1.32123740e-01,  7.88240050e-02,
        -1.09276768e-01,  2.43401504e-01,  2.60124587e-02,
         4.98282622e-03, -8.47025408e-02,  2.40250620e-02,
        -1.47442652e-01,  1.25371154e-01],
       [ 4.31279181e-02, -9.59754355e-02, -3.25854949e-01,
        -2.41987555e-01, -4.96633557e-02,  2.31756700e-01,
        -8.58100926e-02, -2.51532050e-01,  1.58604047e-01,
        -3.27911191e-01, -3.16531695e-01,  2.17014708e-01,
        -2.81172087e-01,  1.84974706e-01, -3.25259861e-02,
        -6.86562674e-02, -8.77374124e-02,  1.06537707e-01,
        -1.44028357e-01,  1.18702942e-01],
       [-5.14774834e-01,  1.48017977e-01, -1.88645090e-01,
        -7.75112564e-01,  2.23308591e-02,  1.47384748e-01,
         1.25066903e-01, -5.00270523e-01,  4.79977287e-02,
        -1.88168557e-01, -1.83310310e-01, -1.30819852e-01,
        -1.72877936e-01,  4.83391146e-01,  1.17716624e-02,
         4.42701904e-02, -6.57108306e-03, -6.48756007e-02,
        -4.01986402e-02,  1.81449410e-01],
       [-4.86343143e-01,  1.20749878e-01, -2.30796688e-01,
        -7.36743968e-01,  9.33262020e-03,  1.91841825e-01,
         7.43213166e-02, -4.66345078e-01,  5.28295505e-02,
        -2.30206250e-01, -2.24255829e-01, -8.14656267e-02,
        -2.12306885e-01,  4.85555629e-01, -2.30278968e-03,
         1.76380031e-02, -1.20921786e-02, -3.25550865e-02,
        -4.49647934e-02,  1.90513851e-01],
       [-4.86247664e-01,  1.00645104e-01, -2.60926548e-01,
        -7.18542016e-01, -1.65350935e-04,  2.25801350e-01,
         3.30135787e-02, -4.59002749e-01,  5.34394209e-02,
        -2.60487192e-01, -2.53879458e-01, -6.03055675e-02,
        -2.41571420e-01,  4.48697708e-01, -1.24950093e-02,
         3.71194475e-03, -1.40150980e-02, -1.72519568e-02,
        -4.57836297e-02,  2.62378591e-01],
       [-3.81728657e-01,  6.76172129e-02, -3.17390622e-01,
        -6.67245980e-01,  5.81021413e-03,  2.71344386e-01,
         1.46064807e-02, -4.35462089e-01,  2.79346542e-02,
        -3.17458773e-01, -3.08895577e-01, -1.16477176e-02,
        -2.89256052e-01,  3.62136228e-01, -6.05141684e-03,
        -1.05430483e-02,  6.02232484e-03,  4.59531661e-03,
        -2.08593253e-02,  2.64035806e-01],
       [-2.50839511e-01,  5.57863993e-02, -3.44395066e-01,
        -4.98476266e-01,  1.50450798e-02,  3.11230848e-01,
         3.10957922e-02, -3.35707231e-01,  9.20749397e-03,
        -3.44688746e-01, -3.36011552e-01,  6.97831731e-02,
        -3.13592833e-01,  3.43969848e-01,  7.88161949e-03,
        -2.33537024e-02,  1.96792923e-02,  3.46562924e-02,
        -2.24208828e-03,  1.44716406e-01],
       [ 1.51724830e-01,  3.96976819e-01,  6.89894571e-02,
         2.84374101e-01,  1.02185772e-01, -6.46442538e-02,
         9.34287072e-02,  3.83901686e-01, -2.64582178e-02,
         7.16887573e-02,  7.02003519e-02, -6.04889542e-04,
         6.90251947e-02,  4.23833857e-01,  9.91409973e-02,
         2.99175818e-02,  3.86307373e-02, -1.13840192e-02,
         2.34519121e-02, -3.55647508e-01],
       [ 2.04904965e-01,  3.49358098e-01,  1.34815987e-01,
         2.89507880e-01,  1.64053683e-01, -1.49621458e-01,
         1.14843032e-01,  3.61550230e-01, -1.48371343e-01,
         1.36529727e-01,  1.33261922e-01, -8.96044974e-02,
         1.28319869e-01,  3.59151968e-01,  1.55353004e-01,
         8.43997313e-02,  1.38699416e-01, -7.01013007e-02,
         1.41104569e-01, -1.91158020e-01],
       [ 2.35494590e-01,  2.98711377e-01,  1.15892032e-01,
         1.91638999e-01,  1.52061392e-01, -1.31894437e-01,
         3.11294245e-02,  2.77580053e-01, -2.07671450e-01,
         1.16779037e-01,  1.11888845e-01, -1.25444657e-01,
         1.10848397e-01,  3.03907585e-01,  1.38287174e-01,
         8.72505599e-02,  1.75519481e-01, -8.18751834e-02,
         1.97753058e-01, -2.77336816e-02],
       [ 3.68373254e-01,  2.62606410e-01,  7.96838866e-03,
         5.16367653e-02,  1.04906251e-01, -4.12930030e-02,
        -7.80992812e-02,  2.28746308e-01, -2.18762277e-01,
         6.83643102e-03,  5.17058947e-03, -8.22956463e-02,
         1.51087133e-02,  2.48603934e-01,  8.96935550e-02,
         4.67140582e-02,  1.74164988e-01, -4.57914410e-02,
         2.08617238e-01,  6.65721631e-02],
       [ 3.71916509e-01,  2.57109913e-01, -4.76526017e-03,
         2.35636011e-02,  1.20528945e-01, -4.39820625e-02,
        -6.87498125e-02,  1.61415806e-01, -2.23456059e-01,
        -6.02921711e-03, -6.11885502e-03, -1.33652556e-01,
         3.69226441e-03,  1.44126782e-01,  1.03175973e-01,
         7.44932286e-02,  1.75344917e-01, -7.87339595e-02,
         2.14870136e-01,  1.37097249e-01],
       [ 3.16520412e-01,  3.00431144e-01,  6.67470943e-02,
        -2.65620903e-02,  1.76993985e-01, -1.46230982e-01,
         1.58700178e-02,  1.05405484e-01, -2.21674948e-01,
         6.51851329e-02,  6.47826050e-02, -2.39917549e-01,
         7.35814152e-02,  1.06719020e-02,  1.57438666e-01,
         1.44064767e-01,  1.85953512e-01, -1.53642541e-01,
         2.14306594e-01,  1.51205901e-01],
       [ 2.46648222e-01,  3.17694957e-01,  4.28196214e-02,
        -1.56221759e-01,  1.97922446e-01, -1.41692548e-01,
         3.68939630e-02,  2.30132722e-02, -2.40133209e-01,
         4.04668858e-02,  4.31431418e-02, -2.84463232e-01,
         5.81570122e-02, -3.14751126e-02,  1.73501708e-01,
         1.57402947e-01,  2.05023609e-01, -1.77338743e-01,
         2.33370416e-01,  2.08144912e-01],
       [ 1.12224087e-01,  1.70468657e-01, -1.16598509e-01,
         5.30076961e-01, -9.46873739e-02,  2.75364263e-01,
        -2.57459502e-01,  2.29559126e-01, -5.46432788e-03,
        -1.13085050e-01, -1.11618996e-01,  2.79069112e-01,
        -1.27446336e-01,  7.15141107e-01, -1.00111762e-01,
        -1.75601800e-01, -1.75601924e-02,  1.96302370e-01,
        -6.13519235e-03, -4.18862019e-02],
       [-5.42722840e-02,  1.34246799e-01, -1.51185155e-01,
         1.42458660e-01, -4.75910969e-02,  2.42663393e-01,
        -1.47073482e-01, -2.30874472e-02, -7.38639029e-02,
        -1.48742802e-01, -1.45524976e-01,  5.15111359e-02,
        -1.59267777e-01,  4.41685591e-01, -5.44327856e-02,
        -7.03512036e-02,  4.19139711e-02,  5.84145162e-02,
         6.12989907e-02,  1.48764785e-01],
       [ 2.53079900e-01,  6.62901418e-02, -2.23906952e-01,
         2.92012084e-01, -5.84484085e-02,  2.92769043e-01,
        -3.29903778e-01,  8.73807058e-02, -6.86550424e-02,
        -2.22511495e-01, -2.18485541e-01,  1.59188300e-01,
        -2.23297539e-01,  2.53485288e-01, -6.67718831e-02,
        -1.08246919e-01,  3.55456422e-02,  1.17412724e-01,
         5.90895920e-02,  2.07777693e-01],
       [ 2.60187061e-01,  6.90003347e-02, -2.84024093e-01,
         3.75236068e-01, -7.71999910e-02,  3.60812433e-01,
        -3.50245826e-01,  1.21897776e-01, -2.64411657e-02,
        -2.82310235e-01, -2.76537489e-01,  2.10276656e-01,
        -2.78468412e-01,  1.73372624e-01, -8.24725960e-02,
        -1.17997900e-01, -2.61493339e-03,  1.34818620e-01,
         1.79626848e-02,  1.60983262e-01],
       [ 2.11837417e-01,  7.02041449e-02, -3.59761468e-01,
         4.19472050e-01, -9.14679867e-02,  4.41426783e-01,
        -3.33447178e-01,  8.94946123e-02,  2.81714912e-02,
        -3.58038179e-01, -3.49902215e-01,  2.64812506e-01,
        -3.43625358e-01,  7.35462241e-02, -9.48348790e-02,
        -1.40260171e-01, -4.46997842e-02,  1.60500731e-01,
        -3.68117709e-02,  6.83363083e-02],
       [ 3.67093631e-01,  4.67646364e-03, -6.12157190e-01,
         6.76766784e-01, -1.61774704e-01,  7.27949275e-01,
        -4.86821801e-01,  2.30749833e-01,  9.31959895e-02,
        -6.10252007e-01, -5.94870863e-01,  5.45092605e-01,
        -5.66592180e-01,  6.22839178e-02, -1.65448976e-01,
        -2.77861960e-01, -1.04247575e-01,  3.27721749e-01,
        -1.03009143e-01, -1.36504458e-01],
       [ 5.80691307e-01,  2.91272615e-01, -3.99014269e-01,
         3.16890553e-01,  5.38710443e-03,  4.25499579e-01,
        -1.23836197e-02,  4.72317543e-01, -9.03242628e-02,
        -3.95530998e-01, -3.85206755e-01,  3.44796530e-01,
        -3.51261592e-01,  2.47223924e-01,  6.60707273e-03,
        -1.42219608e-01,  5.68903403e-02,  1.90189176e-01,
         8.50789073e-02, -6.07332092e-01],
       [ 5.16670648e-01,  3.01702461e-01, -2.55619292e-01,
         2.45529682e-01,  5.89671385e-02,  2.59299930e-01,
         5.54923336e-02,  4.34993351e-01, -1.71122943e-01,
        -2.52804749e-01, -2.46494623e-01,  1.98086246e-01,
        -2.22947191e-01,  2.40928829e-01,  6.21162280e-02,
        -6.31008368e-02,  1.21809215e-01,  9.71366608e-02,
         1.65628121e-01, -4.53952793e-01],
       [ 4.15074920e-01,  3.14783275e-01, -1.19466663e-01,
         1.27819845e-01,  1.11699885e-01,  9.91652210e-02,
         1.15969880e-01,  3.72553229e-01, -2.21964444e-01,
        -1.17418876e-01, -1.16662129e-01,  4.97582090e-02,
        -9.97059911e-02,  1.85776925e-01,  1.12471159e-01,
         1.33399846e-02,  1.67782587e-01,  6.40331676e-03,
         2.17812191e-01, -3.23994712e-01],
       [ 4.44393657e-01,  3.24097446e-01, -3.47440679e-02,
         4.96280688e-02,  1.46655389e-01, -1.43341948e-02,
         1.28824280e-01,  3.31484684e-01, -2.50258878e-01,
        -3.38803181e-02, -3.61727343e-02, -3.72498007e-02,
        -1.96412029e-02,  9.83634115e-02,  1.43554118e-01,
         5.86924333e-02,  2.01291387e-01, -4.47580562e-02,
         2.48575084e-01, -2.17500586e-01],
       [ 3.61821120e-01,  2.84708540e-01, -2.08982601e-02,
        -2.91555793e-02,  1.61242687e-01, -4.33065182e-02,
         1.01339522e-01,  2.74707618e-01, -2.69353924e-01,
        -2.01688634e-02, -2.29887547e-02, -7.73622036e-02,
        -4.52055980e-03,  7.40606588e-02,  1.51199493e-01,
         7.35622475e-02,  2.20071784e-01, -6.50072456e-02,
         2.68012910e-01, -1.55190465e-01],
       [ 2.38350214e-01,  2.68798527e-01, -4.25013930e-03,
        -1.81901653e-01,  1.88679456e-01, -8.86243586e-02,
         1.23611646e-01,  2.10717858e-01, -2.95197173e-01,
        -4.43608948e-03, -6.75456719e-03, -1.43128717e-01,
         1.43874398e-02,  7.35284770e-02,  1.73195255e-01,
         9.99297281e-02,  2.46596580e-01, -1.01482088e-01,
         2.94455704e-01, -1.10944392e-01],
       [ 3.18674255e-01,  2.44663646e-01, -6.50832281e-02,
        -1.61662211e-01,  1.87842058e-01, -3.34170764e-02,
         6.99510837e-02,  2.41664364e-01, -3.31672983e-01,
        -6.67035092e-02, -6.58119647e-02, -8.95812988e-02,
        -3.53868752e-02,  1.28325283e-01,  1.69726435e-01,
         6.49535886e-02,  2.71904222e-01, -6.33696151e-02,
         3.30911230e-01, -7.52392404e-02],
       [ 4.01444188e-01,  4.00217925e-01,  2.26569845e-01,
         3.80212039e-01,  1.12057635e-01, -2.53476191e-01,
         1.03122384e-01,  4.41994600e-01, -3.52023062e-02,
         2.28494317e-01,  2.26439834e-01, -3.67135905e-02,
         2.14476080e-01,  4.31692234e-01,  1.18370604e-01,
         5.62102890e-02,  5.09713730e-02, -3.33467245e-02,
         3.02863902e-02, -2.47073394e-01],
       [ 4.51825195e-01,  3.23704895e-01,  1.90624670e-01,
         4.15047015e-01,  1.29839734e-01, -2.10287042e-01,
         8.02428236e-02,  3.98385173e-01, -1.34643775e-01,
         1.92033615e-01,  1.90644994e-01, -5.90906243e-02,
         1.76608686e-01,  3.82641189e-01,  1.32022446e-01,
         7.07204375e-02,  1.22261260e-01, -4.90986951e-02,
         1.26258328e-01, -1.07297416e-01],
       [ 5.08520831e-01,  2.37834218e-01,  9.52773502e-02,
         3.24504960e-01,  8.13052643e-02, -1.05399519e-01,
        -5.72222280e-02,  2.75693199e-01, -1.70963075e-01,
         9.58845287e-02,  9.50800806e-02, -5.04895998e-02,
         8.72073424e-02,  2.55203601e-01,  8.09481456e-02,
         4.48102381e-02,  1.34041369e-01, -3.06901389e-02,
         1.60556793e-01,  6.92070430e-02],
       [ 5.52191461e-01,  1.97620796e-01,  4.45328673e-02,
         1.66455554e-01,  6.38359292e-02, -7.78155963e-02,
        -1.15973558e-01,  1.95528594e-01, -1.88932024e-01,
         4.28937047e-02,  4.28117177e-02, -6.78185119e-02,
         4.21752189e-02,  1.19150736e-01,  6.24585863e-02,
         4.48291714e-02,  1.44063577e-01, -3.87220046e-02,
         1.77832750e-01,  1.77089671e-01],
       [ 5.43891161e-01,  2.25540480e-01,  8.10860531e-02,
         1.78715237e-01,  8.67882888e-02, -1.22780096e-01,
        -8.46692448e-02,  1.36716995e-01, -1.68154436e-01,
         7.91730908e-02,  7.93792448e-02, -1.29573463e-01,
         7.49166658e-02,  6.69264869e-03,  8.41354753e-02,
         8.43902110e-02,  1.28344398e-01, -8.12696640e-02,
         1.59927868e-01,  2.08193819e-01],
       [ 5.17427908e-01,  2.66085303e-01,  1.21395816e-01,
         1.90584913e-01,  1.08991983e-01, -1.78088789e-01,
        -5.52012794e-02,  1.12627766e-01, -1.29354429e-01,
         1.19544903e-01,  1.19550204e-01, -1.55336038e-01,
         1.16590179e-01, -6.55965382e-02,  1.06340900e-01,
         1.12079708e-01,  1.03411597e-01, -1.06738194e-01,
         1.22318856e-01,  1.55872970e-01],
       [ 4.87926866e-01,  2.52458287e-01, -2.41243277e-02,
         1.67219361e-01,  1.01279483e-01, -3.07078310e-02,
        -1.32707581e-01,  6.29936774e-02, -1.10985686e-01,
        -2.61914902e-02, -1.88169404e-02, -8.43678945e-02,
        -5.64340130e-03, -1.23885635e-01,  8.95116106e-02,
         6.32154366e-02,  8.80454866e-02, -5.81439940e-02,
         1.04030246e-01,  1.51288759e-01]]), array([[-0.86247818,  0.81897933, -0.86875496, -0.87520065,  0.3778028 ,
        -0.87428434,  0.81130348, -0.86763478,  0.81086265,  0.7556926 ],
       [ 0.44327214, -0.42069584,  0.44476529,  0.44867228, -0.17246073,
         0.45349089, -0.41670838,  0.44547848, -0.41265996, -0.37805118],
       [ 0.59180161, -0.56548497,  0.59395941,  0.59960009, -0.26181752,
         0.60124543, -0.56144807,  0.59523361, -0.55722327, -0.51676447],
       [-0.87838865,  0.83381884, -0.88374496, -0.88942893,  0.38830357,
        -0.88762776,  0.82767749, -0.88352446,  0.8268697 ,  0.77054795],
       [ 0.32153808, -0.30437305,  0.3228131 ,  0.32651583, -0.13203557,
         0.32669546, -0.30205958,  0.32340929, -0.30098096, -0.27602157],
       [-0.60755144,  0.57834985, -0.61164795, -0.61542376,  0.28204928,
        -0.6129319 ,  0.57489002, -0.61087047,  0.57409702,  0.54007952],
       [ 0.46164897, -0.44261718,  0.46272031,  0.46555959, -0.21225733,
         0.46960825, -0.43942981,  0.46268583, -0.43651157, -0.4054104 ],
       [-0.67407406,  0.64009011, -0.678449  , -0.68215615,  0.29581168,
        -0.68318034,  0.63395484, -0.67766302,  0.63321348,  0.59191038],
       [-0.39892531,  0.37496393, -0.40280656, -0.4057875 ,  0.17228997,
        -0.40145364,  0.3730033 , -0.40171261,  0.37429952,  0.35233879],

In [ ]:
# try nn

# from sklearn.neural_network import MLPClassifier
# from sklearn.pipeline import make_pipeline
# from sklearn.preprocessing import StandardScaler

# clf_mlp = MLPClassifier(hidden_layer_sizes=[50,50,50], random_state=42)
# pipeline = make_pipeline(Standard)

In [264]:
# feature importances (from random forest)

for name, score in zip(list(X_train), rnd_clf.feature_importances_):
    print(name,":", round(score,2))

lnemp : 0.02
l1_lnemp : 0.03
l3_lnemp : 0.02
l6_lnemp : 0.03
l12_lnemp : 0.02
ur : 0.01
l1_ur : 0.01
l3_ur : 0.02
l6_ur : 0.02
l12_ur : 0.06
lnsp500 : 0.02
l1_lnsp500 : 0.02
l3_lnsp500 : 0.02
l6_lnsp500 : 0.03
l12_lnsp500 : 0.04
lnip : 0.02
l1_lnip : 0.02
l3_lnip : 0.02
l6_lnip : 0.02
l12_lnip : 0.02
r10yr : 0.01
l1_r10yr : 0.01
l2_r10yr : 0.01
l3_r10yr : 0.01
l4_r10yr : 0.01
l5_r10yr : 0.01
l6_r10yr : 0.01
rff : 0.03
l1_rff : 0.05
l2_rff : 0.07
l3_rff : 0.05
l4_rff : 0.04
l5_rff : 0.05
rbaa : 0.01
l1_rbaa : 0.01
l2_rbaa : 0.02
l3_rbaa : 0.01
l4_rbaa : 0.01
l5_rbaa : 0.01
l6_rbaa : 0.02
r3yr : 0.01
l1_r3yr : 0.01
l2_r3yr : 0.01
l3_r3yr : 0.01
l4_r3yr : 0.01
l5_r3yr : 0.01
l6_r3yr : 0.02

In [269]:
# Model: Decision Tree

from sklearn.tree import DecisionTreeClassifier

tree_clf = DecisionTreeClassifier(random_state=42)
tree_clf.fit(X_train, y_train)
y_pred = tree_clf.predict(X_test)
print(tree_clf.__class__.__name__, accuracy_score(y_test, y_pred))

DecisionTreeClassifier 0.9210526315789473

In [270]:
# Model: Bagging ensembles (of Decision Trees)

from sklearn.ensemble import BaggingClassifier

bag_clf = BaggingClassifier(
    DecisionTreeClassifier(random_state=42), n_estimators=500,
    max_samples=350, bootstrap=True, n_jobs=-1, random_state=42) # 100
bag_clf.fit(X_train, y_train)
y_pred = bag_clf.predict(X_test)
print(bag_clf.__class__.__name__, accuracy_score(y_test, y_pred))

BaggingClassifier 0.9868421052631579

In [271]:
# AdaBoost

from sklearn.ensemble import AdaBoostClassifier

ada_clf = AdaBoostClassifier(
    DecisionTreeClassifier(max_depth=2), n_estimators=200, # 2 200
    algorithm="SAMME.R", learning_rate=0.5, random_state=42)
ada_clf.fit(X_train, y_train)
y_pred = ada_clf.predict(X_test)
print(ada_clf.__class__.__name__, accuracy_score(y_test, y_pred))

AdaBoostClassifier 0.9605263157894737

In [272]:
# Random forest parameters

rnd_clf2 = RandomForestClassifier(n_estimators=500, max_leaf_nodes=32, n_jobs=-1, random_state=42)
rnd_clf2.fit(X_train, y_train)
y_pred = rnd_clf2.predict(X_test)
display(accuracy_score(y_test, y_pred))

0.993421052631579

In [414]:
# Train/test/validate error

for clf in (log_clf, rnd_clf, svm_clf, voting_clf, tree_clf, bag_clf, ada_clf, rnd_clf2, mlp_clf, mlp_clf2):
    y_pred_train = clf.predict(X_train)
    y_pred_test = clf.predict(X_test)
    y_pred_valid = clf.predict(X_valid)
    print(clf.__class__.__name__,"- train:", round(accuracy_score(y_train, y_pred_train),4), "- test:", round(accuracy_score(y_test, y_pred_test),4), "- validate:", round(accuracy_score(y_valid, y_pred_valid),4))

LogisticRegression - train: 0.9077 - test: 0.8882 - validate: 0.5385
RandomForestClassifier - train: 1.0 - test: 0.9868 - validate: 0.4615
SVC - train: 0.9127 - test: 0.9145 - validate: 0.5
VotingClassifier - train: 0.9769 - test: 0.9737 - validate: 0.5
DecisionTreeClassifier - train: 1.0 - test: 0.9211 - validate: 0.6538
BaggingClassifier - train: 0.9984 - test: 0.9868 - validate: 0.4615
AdaBoostClassifier - train: 1.0 - test: 0.9605 - validate: 0.4615
RandomForestClassifier - train: 1.0 - test: 0.9934 - validate: 0.4615
MLPClassifier - train: 0.8962 - test: 0.8882 - validate: 0.7692
MLPClassifier - train: 0.9819 - test: 0.9868 - validate: 0.9615

In [415]:
# Predictions on random set of test data

pred_test = log_clf.predict_proba(X_test)
dfpred_test = pd.DataFrame(pred_test, index = X_test.index.values)
pred_test2 = mlp_clf2.predict_proba(X_test) # svm_clf mlp_clf2
dfpred_test2 = pd.DataFrame(pred_test2, index = X_test.index.values)
xb_test = pd.concat([y_test,X_test,dfpred_test,dfpred_test2], axis=1)
xb_test #.tail()

,rec12mo,lnemp,l1_lnemp,l3_lnemp,l6_lnemp,l12_lnemp,ur,l1_ur,l3_ur,l6_ur,...,l1_r3yr,l2_r3yr,l3_r3yr,l4_r3yr,l5_r3yr,l6_r3yr,0,1,0,1
413,0.0,0.273190,0.270630,0.263816,0.254734,0.244021,0.017967,0.080518,0.206039,0.456576,...,0.835187,0.749945,0.780951,0.844637,0.624557,0.391131,0.918405,0.081595,0.993036,0.006964
535,0.0,0.840901,0.836850,0.823810,0.821213,0.804030,-0.830994,-0.767765,-0.702587,-0.636557,...,0.140867,0.189549,0.218402,0.198168,0.277676,0.339521,0.938798,0.061202,0.993551,0.006449
117,0.0,-1.523285,-1.521606,-1.508306,-1.505504,-1.514009,-0.112643,-0.245745,-0.313175,-0.315048,...,-0.642225,-0.631940,-0.654189,-0.630720,-0.615223,-0.563657,0.775785,0.224215,0.918841,0.081159
531,0.0,0.814008,0.810190,0.804290,0.792440,0.781309,-0.635080,-0.572008,-0.507881,-0.379350,...,0.267683,0.329648,0.394198,0.319781,0.210226,0.255654,0.959310,0.040690,0.995767,0.004233
129,0.0,-1.451426,-1.451747,-1.443337,-1.450491,-1.449300,-0.177947,-0.245745,-0.248274,-0.186444,...,-0.439319,-0.456816,-0.481589,-0.499506,-0.515655,-0.518499,0.828398,0.171602,0.925151,0.074849
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
567,1.0,1.026510,1.025798,1.028267,1.018341,1.002723,-1.222823,-1.224533,-1.351605,-1.215275,...,0.327921,0.441090,0.314291,0.367786,0.409362,0.362100,0.423294,0.576706,0.107987,0.892013
358,0.0,-0.153973,-0.146977,-0.144495,-0.111636,-0.044889,2.956679,2.951629,3.191525,2.514238,...,1.345624,1.431335,1.471353,1.676726,2.137346,2.339416,0.952539,0.047461,0.992826,0.007174
326,1.0,-0.114622,-0.099614,-0.071689,-0.068683,-0.059667,1.128147,1.059305,0.270941,0.070764,...,1.282215,2.112725,2.772248,2.387201,1.767982,1.723319,0.000179,0.999821,0.000156,0.999844
301,0.0,-0.235646,-0.242927,-0.275467,-0.288365,-0.333181,0.083272,0.145770,0.270941,0.585179,...,0.778120,0.737208,0.733007,0.713423,0.618134,0.597572,0.984373,0.015627,0.977890,0.022110
352,1.0,-0.139089,-0.129302,-0.100722,-0.072236,-0.012603,2.564851,2.560114,2.282899,1.935520,...,2.727924,2.896005,2.682751,2.816047,2.811838,3.020025,0.087543,0.912457,0.001603,0.998397

In [416]:
# Predictions on validation data

pred_valid = log_clf.predict_proba(X_valid)
dfpred_valid = pd.DataFrame(pred_valid, index = df2_valid.index.values)
pred_valid2 = mlp_clf2.predict_proba(X_valid) # svm_clf mlp_clf2
dfpred_valid2 = pd.DataFrame(pred_valid2, index = df2_valid.index.values)
xb_valid = pd.concat([df2_valid,dfpred_valid,dfpred_valid2], axis=1)
xb_valid

,period,rec12mo,lnemp,l1_lnemp,l3_lnemp,l6_lnemp,l12_lnemp,ur,l1_ur,l3_ur,...,l1_r3yr,l2_r3yr,l3_r3yr,l4_r3yr,l5_r3yr,l6_r3yr,0,1,0,1
779,3/1/2018,0.0,11.906858,11.905332,11.901726,11.898181,11.891198,4.0,4.1,4.1,...,2.36,2.15,1.96,1.81,1.68,1.51,9.262387e-01,0.073761,0.960214,0.039786
780,4/1/2018,0.0,11.907842,11.906858,11.902715,11.899181,11.892546,4.0,4.0,4.0,...,2.42,2.36,2.15,1.96,1.81,1.68,9.105166e-01,0.089483,0.949831,0.050169
781,5/1/2018,0.0,11.910056,11.907842,11.905332,11.900736,11.894023,3.8,4.0,4.1,...,2.52,2.42,2.36,2.15,1.96,1.81,9.245451e-01,0.075455,0.954780,0.045220
782,6/1/2018,0.0,11.911487,11.910056,11.906858,11.901726,11.895381,4.0,3.8,4.0,...,2.66,2.52,2.42,2.36,2.15,1.96,8.840906e-01,0.115909,0.922302,0.077698
783,7/1/2018,0.0,11.911856,11.911487,11.907842,11.902715,11.896636,3.8,4.0,4.0,...,2.65,2.66,2.52,2.42,2.36,2.15,9.060537e-01,0.093946,0.927247,0.072753
784,8/1/2018,0.0,11.913539,11.911856,11.910056,11.905332,11.897555,3.8,3.8,3.8,...,2.70,2.65,2.66,2.52,2.42,2.36,9.157244e-01,0.084276,0.941709,0.058291
785,9/1/2018,0.0,11.914121,11.913539,11.911487,11.906858,11.898181,3.7,3.8,4.0,...,2.71,2.70,2.65,2.66,2.52,2.42,9.238367e-01,0.076163,0.925000,0.075000
786,10/1/2018,0.0,11.915219,11.914121,11.911856,11.907842,11.899181,3.8,3.7,3.8,...,2.84,2.71,2.70,2.65,2.66,2.52,8.887994e-01,0.111201,0.872321,0.127679
787,11/1/2018,0.0,11.915867,11.915219,11.913539,11.910056,11.900736,3.8,3.8,3.8,...,2.94,2.84,2.71,2.70,2.65,2.66,8.347401e-01,0.165260,0.783495,0.216505
788,12/1/2018,0.0,11.917083,11.915867,11.914121,11.911487,11.901726,3.9,3.8,3.7,...,2.91,2.94,2.84,2.71,2.70,2.65,7.507279e-01,0.249272,0.668742,0.331258
789,1/1/2019,0.0,11.918804,11.917083,11.915219,11.911856,11.902715,4.0,3.9,3.8,...,2.67,2.91,2.94,2.84,2.71,2.70,6.086435e-01,0.391357,0.421895,0.578105
790,2/1/2019,0.0,11.918837,11.918804,11.915867,11.913539,11.905332,3.8,4.0,3.8,...,2.52,2.67,2.91,2.94,2.84,2.71,6.666970e-01,0.333303,0.500232,0.499768
791,3/1/2019,1.0,11.920349,11.918837,11.917083,11.914121,11.906858,3.8,3.8,3.9,...,2.48,2.52,2.67,2.91,2.94,2.84,6.693744e-01,0.330626,0.418168,0.581832
792,4/1/2019,1.0,11.922396,11.920349,11.918804,11.915219,11.907842,3.7,3.8,4.0,...,2.37,2.48,2.52,2.67,2.91,2.94,7.519968e-01,0.248003,0.488365,0.511635
793,5/1/2019,1.0,11.922648,11.922396,11.918837,11.915867,11.910056,3.6,3.7,3.8,...,2.31,2.37,2.48,2.52,2.67,2.91,7.002385e-01,0.299762,0.349645,0.650355
794,6/1/2019,1.0,11.924001,11.922648,11.920349,11.917083,11.911487,3.6,3.6,3.8,...,2.16,2.31,2.37,2.48,2.52,2.67,6.603453e-01,0.339655,0.390476,0.609524
795,7/1/2019,1.0,11.924598,11.924001,11.922396,11.918804,11.911856,3.7,3.6,3.7,...,1.78,2.16,2.31,2.37,2.48,2.52,5.853992e-01,0.414601,0.257457,0.742543
796,8/1/2019,1.0,11.926061,11.924598,11.922648,11.918837,11.913539,3.6,3.7,3.6,...,1.80,1.78,2.16,2.31,2.37,2.48,5.496011e-01,0.450399,0.222238,0.777762
797,9/1/2019,1.0,11.927403,11.926061,11.924001,11.920349,11.914121,3.5,3.6,3.6,...,1.51,1.80,1.78,2.16,2.31,2.37,5.649535e-01,0.435047,0.215623,0.784377
798,10/1/2019,1.0,11.928064,11.927403,11.924598,11.922396,11.915219,3.6,3.5,3.7,...,1.59,1.51,1.80,1.78,2.16,2.31,5.308531e-01,0.469147,0.225784,0.774216
799,11/1/2019,1.0,11.929436,11.928064,11.926061,11.922648,11.915867,3.6,3.6,3.6,...,1.53,1.59,1.51,1.80,1.78,2.16,5.251766e-01,0.474823,0.206372,0.793628
800,12/1/2019,1.0,11.930266,11.929436,11.927403,11.924001,11.917083,3.6,3.6,3.5,...,1.61,1.53,1.59,1.51,1.80,1.78,5.378022e-01,0.462198,0.287855,0.712145
801,1/1/2020,1.0,11.931932,11.930266,11.928064,11.924598,11.918804,3.6,3.6,3.6,...,1.63,1.61,1.53,1.59,1.51,1.80,5.828868e-01,0.417113,0.469489,0.530511
802,2/1/2020,1.0,11.933667,11.931932,11.929436,11.926061,11.918837,3.5,3.6,3.6,...,1.52,1.63,1.61,1.53,1.59,1.51,5.658338e-01,0.434166,0.433180,0.566820
803,3/1/2020,1.0,11.924359,11.933667,11.930266,11.927403,11.920349,4.4,3.5,3.6,...,1.31,1.52,1.63,1.61,1.53,1.59,1.720888e-01,0.827911,0.114162,0.885838
804,4/1/2020,1.0,11.778523,11.924359,11.931932,11.928064,11.922396,14.8,4.4,3.6,...,0.50,1.31,1.52,1.63,1.61,1.53,1.243958e-07,1.000000,0.002532,0.997468

In [417]:
# Predictions on out-of-sample data

pred_oos = log_clf.predict_proba(X_oos)
dfpred_oos = pd.DataFrame(pred_oos, index = df2_oos.index.values)
pred_oos2 = mlp_clf2.predict_proba(X_oos) # svm_clf mlp_clf2
dfpred_oos2 = pd.DataFrame(pred_oos2, index = df2_oos.index.values)
xb_oos = pd.concat([df2_oos,dfpred_oos,dfpred_oos2], axis=1)
xb_oos.tail(48) # 18

,period,rec12mo,lnemp,l1_lnemp,l3_lnemp,l6_lnemp,l12_lnemp,ur,l1_ur,l3_ur,...,l1_r3yr,l2_r3yr,l3_r3yr,l4_r3yr,l5_r3yr,l6_r3yr,0,1,0,1
805,5/1/2020,NaN,11.798405,11.778523,11.933667,11.929436,11.922648,13.2,14.8,3.5,...,0.28,0.50,1.31,1.52,1.63,1.61,2.447047e-07,1.000000,0.004639,0.995361
806,6/1/2020,NaN,11.832506,11.798405,11.924359,11.930266,11.924001,11.0,13.2,4.4,...,0.22,0.28,0.50,1.31,1.52,1.63,1.855502e-05,0.999981,0.007117,0.992883
807,7/1/2020,NaN,11.843954,11.832506,11.778523,11.931932,11.924598,10.2,11.0,14.8,...,0.22,0.22,0.28,0.50,1.31,1.52,9.652506e-02,0.903475,0.005385,0.994615
808,8/1/2020,NaN,11.854911,11.843954,11.798405,11.933667,11.926061,8.4,10.2,13.2,...,0.17,0.22,0.22,0.28,0.50,1.31,4.118522e-01,0.588148,0.027773,0.972227
809,9/1/2020,NaN,11.862314,11.854911,11.832506,11.924359,11.927403,7.8,8.4,11.0,...,0.16,0.17,0.22,0.22,0.28,0.50,5.255744e-01,0.474426,0.154713,0.845287
810,10/1/2020,NaN,11.867048,11.862314,11.843954,11.778523,11.928064,6.8,7.8,10.2,...,0.16,0.16,0.17,0.22,0.22,0.28,9.998357e-01,0.000164,0.999015,0.000985
811,11/1/2020,NaN,11.868927,11.867048,11.854911,11.798405,11.929436,6.7,6.8,8.4,...,0.19,0.16,0.16,0.17,0.22,0.22,9.984694e-01,0.001531,0.998696,0.001304
812,12/1/2020,NaN,11.867224,11.868927,11.862314,11.832506,11.930266,6.7,6.7,7.8,...,0.22,0.19,0.16,0.16,0.17,0.22,9.888369e-01,0.011163,0.995309,0.004691
813,1/1/2021,NaN,11.870012,11.867224,11.867048,11.843954,11.931932,6.4,6.7,6.8,...,0.19,0.22,0.19,0.16,0.16,0.17,9.748256e-01,0.025174,0.991247,0.008753
814,2/1/2021,NaN,11.873693,11.870012,11.868927,11.854911,11.933667,6.2,6.4,6.7,...,0.20,0.19,0.22,0.19,0.16,0.16,9.211378e-01,0.078862,0.968264,0.031736
815,3/1/2021,NaN,11.879470,11.873693,11.867224,11.862314,11.924359,6.1,6.2,6.7,...,0.21,0.20,0.19,0.22,0.19,0.16,9.357663e-01,0.064234,0.988387,0.011613
816,4/1/2021,NaN,11.881678,11.879470,11.870012,11.867048,11.778523,6.1,6.1,6.4,...,0.32,0.21,0.20,0.19,0.22,0.19,9.810046e-01,0.018995,0.999743,0.000257
817,5/1/2021,NaN,11.884792,11.881678,11.873693,11.868927,11.798405,5.8,6.1,6.2,...,0.35,0.32,0.21,0.20,0.19,0.22,9.781841e-01,0.021816,0.999713,0.000287
818,6/1/2021,NaN,11.890142,11.884792,11.879470,11.867224,11.832506,5.9,5.8,6.1,...,0.32,0.35,0.32,0.21,0.20,0.19,9.686116e-01,0.031388,0.999622,0.000378
819,7/1/2021,NaN,11.896561,11.890142,11.881678,11.870012,11.843954,5.4,5.9,6.1,...,0.39,0.32,0.35,0.32,0.21,0.20,9.823628e-01,0.017637,0.999596,0.000404
820,8/1/2021,NaN,11.899724,11.896561,11.884792,11.873693,11.854911,5.1,5.4,5.8,...,0.40,0.39,0.32,0.35,0.32,0.21,9.815243e-01,0.018476,0.999425,0.000575
821,9/1/2021,NaN,11.902979,11.899724,11.890142,11.879470,11.862314,4.7,5.1,5.9,...,0.42,0.40,0.39,0.32,0.35,0.32,9.900731e-01,0.009927,0.999393,0.000607
822,10/1/2021,NaN,11.908785,11.902979,11.896561,11.881678,11.867048,4.5,4.7,5.4,...,0.47,0.42,0.40,0.39,0.32,0.35,9.870567e-01,0.012943,0.999141,0.000859
823,11/1/2021,NaN,11.913023,11.908785,11.899724,11.884792,11.868927,4.1,4.5,5.1,...,0.67,0.47,0.42,0.40,0.39,0.32,9.889479e-01,0.011052,0.999138,0.000862
824,12/1/2021,NaN,11.916809,11.913023,11.902979,11.890142,11.867224,3.9,4.1,4.7,...,0.82,0.67,0.47,0.42,0.40,0.39,9.888540e-01,0.011146,0.999203,0.000797
825,1/1/2022,NaN,11.918484,11.916809,11.908785,11.896561,11.870012,4.0,3.9,4.5,...,0.95,0.82,0.67,0.47,0.42,0.40,9.748556e-01,0.025144,0.998826,0.001174
826,2/1/2022,NaN,11.924214,11.918484,11.913023,11.899724,11.873693,3.8,4.0,4.1,...,1.25,0.95,0.82,0.67,0.47,0.42,9.624843e-01,0.037516,0.998531,0.001469
827,3/1/2022,NaN,11.927482,11.924214,11.916809,11.902979,11.879470,3.6,3.8,3.9,...,1.65,1.25,0.95,0.82,0.67,0.47,9.573249e-01,0.042675,0.998328,0.001672
828,4/1/2022,NaN,11.929278,11.927482,11.918484,11.908785,11.881678,3.7,3.6,4.0,...,2.09,1.65,1.25,0.95,0.82,0.67,9.521478e-01,0.047852,0.998197,0.001803
829,5/1/2022,NaN,11.931162,11.929278,11.924214,11.913023,11.884792,3.6,3.7,3.8,...,2.72,2.09,1.65,1.25,0.95,0.82,9.025626e-01,0.097437,0.997003,0.002997
830,6/1/2022,NaN,11.933923,11.931162,11.927482,11.916809,11.890142,3.6,3.6,3.6,...,2.79,2.72,2.09,1.65,1.25,0.95,8.545131e-01,0.145487,0.996792,0.003208
831,7/1/2022,NaN,11.938442,11.933923,11.929278,11.918484,11.896561,3.5,3.6,3.7,...,3.15,2.79,2.72,2.09,1.65,1.25,8.648913e-01,0.135109,0.995560,0.004440
832,8/1/2022,NaN,11.940028,11.938442,11.931162,11.924214,11.899724,3.6,3.5,3.6,...,3.03,3.15,2.79,2.72,2.09,1.65,7.929704e-01,0.207030,0.990935,0.009065
833,9/1/2022,NaN,11.941690,11.940028,11.933923,11.927482,11.902979,3.5,3.6,3.6,...,3.23,3.03,3.15,2.79,2.72,2.09,7.546034e-01,0.245397,0.976109,0.023891
834,10/1/2022,NaN,11.944039,11.941690,11.938442,11.929278,11.908785,3.6,3.5,3.5,...,3.88,3.23,3.03,3.15,2.79,2.72,6.339734e-01,0.366027,0.929478,0.070522
835,11/1/2022,NaN,11.945714,11.944039,11.940028,11.931162,11.913023,3.6,3.6,3.6,...,4.38,3.88,3.23,3.03,3.15,2.79,4.676869e-01,0.532313,0.720054,0.279946
836,12/1/2022,NaN,11.946596,11.945714,11.941690,11.933923,11.916809,3.5,3.6,3.5,...,4.34,4.38,3.88,3.23,3.03,3.15,3.452054e-01,0.654795,0.470353,0.529647
837,1/1/2023,NaN,11.949715,11.946596,11.944039,11.938442,11.918484,3.4,3.5,3.6,...,4.05,4.34,4.38,3.88,3.23,3.03,2.519798e-01,0.748020,0.316723,0.683277
838,2/1/2023,NaN,11.951567,11.949715,11.945714,11.940028,11.924214,3.6,3.4,3.6,...,3.91,4.05,4.34,4.38,3.88,3.23,1.981463e-01,0.801854,0.147130,0.852870
839,3/1/2023,NaN,11.952509,11.951567,11.946596,11.941690,11.927482,3.5,3.6,3.5,...,4.23,3.91,4.05,4.34,4.38,3.88,1.860281e-01,0.813972,0.055369,0.944631
840,4/1/2023,NaN,11.954298,11.952509,11.949715,11.944039,11.929278,3.4,3.5,3.4,...,4.09,4.23,3.91,4.05,4.34,4.38,1.469016e-01,0.853098,0.033932,0.966068
841,5/1/2023,NaN,11.956245,11.954298,11.951567,11.945714,11.931162,3.7,3.4,3.6,...,3.76,4.09,4.23,3.91,4.05,4.34,5.726812e-02,0.942732,0.010668,0.989332
842,6/1/2023,NaN,11.957784,11.956245,11.952509,11.946596,11.933923,3.6,3.7,3.5,...,3.82,3.76,4.09,4.23,3.91,4.05,4.028177e-02,0.959718,0.007427,0.992573
843,7/1/2023,NaN,11.958963,11.957784,11.954298,11.949715,11.938442,3.5,3.6,3.4,...,4.27,3.82,3.76,4.09,4.23,3.91,3.995399e-02,0.960046,0.006748,0.993252
844,8/1/2023,NaN,11.960306,11.958963,11.956245,11.951567,11.940028,3.8,3.5,3.7,...,4.47,4.27,3.82,3.76,4.09,4.23,3.108815e-02,0.968912,0.006200,0.993800
845,9/1/2023,NaN,11.961878,11.960306,11.957784,11.952509,11.941690,3.8,3.8,3.6,...,4.59,4.47,4.27,3.82,3.76,4.09,2.303576e-02,0.976964,0.004203,0.995797
846,10/1/2023,NaN,11.962930,11.961878,11.958963,11.954298,11.944039,3.8,3.8,3.5,...,4.74,4.59,4.47,4.27,3.82,3.76,1.568835e-02,0.984312,0.004081,0.995919
847,11/1/2023,NaN,11.964090,11.962930,11.960306,11.956245,11.945714,3.7,3.8,3.8,...,4.89,4.74,4.59,4.47,4.27,3.82,3.030233e-02,0.969698,0.006972,0.993028
848,12/1/2023,NaN,11.965936,11.964090,11.961878,11.957784,11.946596,3.7,3.7,3.8,...,4.64,4.89,4.74,4.59,4.47,4.27,3.650785e-02,0.963492,0.007629,0.992371
849,1/1/2024,NaN,11.967562,11.965936,11.962930,11.958963,11.949715,3.7,3.7,3.8,...,4.19,4.64,4.89,4.74,4.59,4.47,3.950830e-02,0.960492,0.006284,0.993716
850,2/1/2024,NaN,11.969058,11.967562,11.964090,11.960306,11.951567,3.9,3.7,3.7,...,4.11,4.19,4.64,4.89,4.74,4.59,5.326385e-02,0.946736,0.008042,0.991958
851,3/1/2024,NaN,11.971053,11.969058,11.965936,11.961878,11.952509,3.8,3.9,3.7,...,4.33,4.11,4.19,4.64,4.89,4.74,8.193325e-02,0.918067,0.008229,0.991771
852,4/1/2024,NaN,11.972159,11.971053,11.967562,11.962930,11.954298,3.9,3.8,3.7,...,4.38,4.33,4.11,4.19,4.64,4.89,7.084388e-02,0.929156,0.006523,0.993477

In [ ]:
# get plot to accept more than two X vars in classifier (but still only charting 2)
# x add more vars to classifier
# x see if way to play with svm parameters? higher dimensions?
# x play with random forest/bagging parameters? (see other notebook)
# x change from rec to rec12mo?
# x predict values for full df (look at months leading up to covid rec)
# x any other features? IP, more interest rates, 3/6/9/12mo growth rates?

# more growth rates (3 and 9) and do interest rate spreads instead of levels (maybe keep rff level too...)
# x calc training/test/(valid?) errors
# x should i keep the 2020 recession as out of sample too? just the rec12mo period, or also the expansion before?

# look at diff ensemble regressions to use (see other notebook and google results)
# sqrt rectime?

# try training a model on each expansion/recession time period window, then average all predictions together?
# try training a model for expansion/prerecession/recession?

# standardscaler: might want to select X subset, scale, then calc lags, etc. (but then how to scale new cols after...?)

# rectime
# monthly or daily?
# linear or sqrt?
# standardscaler?
# split test data into each expansion/recession time period window (rolling cross validation?)
# continue to leave last exp/rec (covid) for validation
# loop over activations, alphas, neurons, solvers...